### PR TITLE
Fix an error that prevents any text layers from being imported

### PR DESCRIPTION
**Pull request by rodionovd**
## Steps to Reproduce

1. Take a .fig document with at least one text layer and try to convert it to .sketch

## Expected Results

The generated .sketch file contains all text layers from the original Figma document.

## Actual Results

1. The tool reports the following error:

```
ERROR:root:An unexpected error occurred when converting TEXT: another ((3, 58)). It will be skipped
Traceback (most recent call last):
  File "converter/tree.py", line 74, in convert_node
  File "converter/tree.py", line 62, in convert_node
  File "converter/text.py", line 81, in convert
  File "converter/text.py", line 201, in override_characters_style
KeyError: 'styleID'
```

2. There're no text layers in the generated .sketch document.

## Solution

The culprit is emoji detection logic when text layer attributes are prepared: instead of a special fill style override for emojis there's now a glyph-level "emojiCodePoints" field that we should use to detect them.

## Testing

I've updated `tests/data/structure.fig` to the latest Figma file format version so running

```bash
pytest tests/integration/test_structure.py::test_page
```

will now trigger the error.

> [!NOTE]
> There're other test cases in `test_structure.py` that fail for a different reason – see #104 

--------

Now, I'm not 100% happy with this PR:

1. Do we need to be backwards-compatible with the previous versions of .fig file format? I've left the old code branch intact but the more I think about it the less I'm inclined to keep it around. So what's fig2sketch's official stance on maintaining backward compatibility?

2. What does the process of updating .fig files used in tests look like? I've imported `tests/data/structure.fig` to Figma and immediately downloaded it back – is this enough? I guess the same trick will work for `tests/data/vector.fig` but `tests/data/broken_images.fig` seemingly requires an additional step to corrupt one of the bundled images – and I couldn't find a script that does it anywhere in the repo.

### CODE REVIEW

**Comment by tmdvs** [comment]
@rodionovd You should be able to rebase `main` into your branches and 🤞 the GitHub actions will pass 🚥

**Comment by rodionovd** [comment]
@tmdvs all green now!

**Comment by tmdvs** [comment]
> Do we need to be backwards-compatible with the previous versions of .fig file format? I've left the old code branch intact but the more I think about it the less I'm inclined to keep it around. So what's fig2sketch's official stance on maintaining backward compatibility?

I've checked in with some of the team on this one. Given we keep older `fig2sketch` releases available here on GitHub and the ease with which you can migrate older `fig` documents to newer schemas using Figma, there is no need to keep the code backwards-compatible.

This is a good example where we wouldn't need to worry too much. So feel free to drop that older code path, and we can get this merged in :shipit:

**Comment by rodionovd** [comment]
> This is a good example where we wouldn't need to worry too much. So feel free to drop that older code path, and we can get this merged in :shipit:

The old code path is no more 👋

**Review by tmdvs — APPROVED** [review]

**Pull request merged**
